// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4EdVSj3wIxfuGqxRolE71k7UMaL5wL8',
    appId: '1:235726905152:web:c8f20ef5451f6db75264a5',
    messagingSenderId: '235726905152',
    projectId: 'todo-app-ww-2026',
    authDomain: 'todo-app-ww-2026.firebaseapp.com',
    storageBucket: 'todo-app-ww-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHN2siHG1BeAn3Qz5P4cNgTjwtEe9G_xY',
    appId: '1:235726905152:android:8c0fbe37901bc62d5264a5',
    messagingSenderId: '235726905152',
    projectId: 'todo-app-ww-2026',
    storageBucket: 'todo-app-ww-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-9TtlqqtPT2BuxARFLG4_8JaY7sEJWE',
    appId: '1:235726905152:ios:3208a072fbb1496c5264a5',
    messagingSenderId: '235726905152',
    projectId: 'todo-app-ww-2026',
    storageBucket: 'todo-app-ww-2026.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-9TtlqqtPT2BuxARFLG4_8JaY7sEJWE',
    appId: '1:235726905152:ios:3208a072fbb1496c5264a5',
    messagingSenderId: '235726905152',
    projectId: 'todo-app-ww-2026',
    storageBucket: 'todo-app-ww-2026.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF4EdVSj3wIxfuGqxRolE71k7UMaL5wL8',
    appId: '1:235726905152:web:362e175afb5d01da5264a5',
    messagingSenderId: '235726905152',
    projectId: 'todo-app-ww-2026',
    authDomain: 'todo-app-ww-2026.firebaseapp.com',
    storageBucket: 'todo-app-ww-2026.firebasestorage.app',
  );
}
